#!/bin/bash
year=$1
day=$2
token=$(cat /home/dan/Desktop/advent-of-code/cookie.txt)

YEAR_DIR=~/Desktop/advent-of-code/${year}
DAY_DIR="${YEAR_DIR}/${day}"
INPUT_FILE="${DAY_DIR}/input.txt"
CODE_FILE="${DAY_DIR}/main.c"

if test -f $INPUT_FILE
then
    echo "Input Already Exists"
    exit 0
fi

url="https://adventofcode.com/${year}/day/${day}/input"
echo "Downloading input for ${url}"

response=$(curl -sB --cookie "session=${token}" $url -H "Connection: close")

if [ "$response" == "$(cat ./unavailable_date.txt)" ]
then
    echo "No Puzzle Available"
    exit 1
fi

if [ ! -d $DAY_DIR ]
then
    mkdir -p $DAY_DIR
    echo "Creating $DAY_DIR"
fi

echo "$response" >> $INPUT_FILE
echo "File saved"

cp /home/dan/Desktop/advent-of-code/scripts/main.c $DAY_DIR
echo "Created skeleton .c file"
